name: "Deploy para VPS"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.ftp_password }}
          source: "."
          target: "/sistema"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          key: ${{ secrets.ftp_password }}
          script: |
            cd /app
            composer install --no-dev --no-progress -a
            php artisan optimize
            chown -R www-data:www-data .